#!/usr/bin/env python3
"""
social-to-discord
------------------
Polls RSS feeds (generated by RSSHub) for social media accounts and posts
new items to a Discord channel via webhook, with a fully custom caption
per platform.

Run this on a schedule (see .github/workflows/social-to-discord.yml).
State (which post IDs have already been sent) is kept in state.json so
the same post is never sent twice.
"""

import json
import os
import re
import sys
import time
from pathlib import Path

import feedparser
import requests

ROOT = Path(__file__).parent
CONFIG_PATH = ROOT / "config.json"
STATE_PATH = ROOT / "state.json"

REQUEST_TIMEOUT = 20
MAX_SUMMARY_CHARS = 350


def load_json(path, default):
    if path.exists():
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return default


def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def clean_summary(html_summary: str) -> str:
    """Strip HTML tags from the RSS summary and trim it to a readable length."""
    if not html_summary:
        return ""
    text = re.sub(r"<[^>]+>", " ", html_summary)
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) > MAX_SUMMARY_CHARS:
        text = text[:MAX_SUMMARY_CHARS].rsplit(" ", 1)[0] + "…"
    return text


def extract_thumbnail(entry) -> str | None:
    """Best-effort: pull the first <img src="..."> out of the entry, if any."""
    html_blob = ""
    if "summary" in entry:
        html_blob += entry.summary
    if "media_content" in entry and entry.media_content:
        return entry.media_content[0].get("url")
    if "media_thumbnail" in entry and entry.media_thumbnail:
        return entry.media_thumbnail[0].get("url")
    match = re.search(r'<img[^>]+src="([^"]+)"', html_blob)
    return match.group(1) if match else None


def build_payload(feed_cfg: dict, entry) -> dict:
    account = feed_cfg["name"]
    link = entry.get("link", "")
    summary = clean_summary(entry.get("summary", entry.get("title", "")))
    caption = feed_cfg["caption_template"].format(
        account=account,
        link=link,
        summary=summary,
        title=entry.get("title", ""),
    )

    embed = {
        "description": caption,
        "color": feed_cfg.get("color", 0x5865F2),
        "url": link if link else None,
    }
    thumb = extract_thumbnail(entry)
    if thumb:
        embed["image"] = {"url": thumb}

    return {"embeds": [embed]}


def send_to_discord(webhook_url: str, payload: dict) -> bool:
    resp = requests.post(webhook_url, json=payload, timeout=REQUEST_TIMEOUT)
    if resp.status_code not in (200, 204):
        print(f"  ! Discord webhook error {resp.status_code}: {resp.text}", file=sys.stderr)
        return False
    return True


def main():
    config = load_json(CONFIG_PATH, {})
    state = load_json(STATE_PATH, {})
    rsshub_base = config.get("rsshub_base", "https://rsshub.app")

    any_new = False

    for feed_cfg in config.get("feeds", []):
        feed_key = feed_cfg["name"]
        # YouTube (and anything else with its own free official feed) sets
        # "feed_url" directly. Instagram/TikTok/LinkedIn set "route" and go
        # through RSSHub instead, since they have no free official feed.
        if feed_cfg.get("feed_url"):
            feed_url = feed_cfg["feed_url"]
        else:
            feed_url = rsshub_base.rstrip("/") + feed_cfg["route"]
        webhook_url = os.environ.get(feed_cfg["webhook_env"], "")

        if not webhook_url:
            print(f"[skip] {feed_key}: env var {feed_cfg['webhook_env']} not set")
            continue

        print(f"[check] {feed_key} -> {feed_url}")
        try:
            parsed = feedparser.parse(feed_url)
        except Exception as e:
            print(f"  ! failed to fetch feed: {e}", file=sys.stderr)
            continue

        if parsed.bozo and not parsed.entries:
            print(f"  ! feed returned no entries (platform may be blocking scraping)")
            continue

        seen_ids = set(state.get(feed_key, []))
        new_ids = []

        # Process oldest-first so Discord message order matches posting order
        for entry in reversed(parsed.entries):
            entry_id = entry.get("id") or entry.get("link")
            if not entry_id or entry_id in seen_ids:
                continue

            payload = build_payload(feed_cfg, entry)
            ok = send_to_discord(webhook_url, payload)
            if ok:
                print(f"  -> posted: {entry.get('title', entry_id)[:80]}")
                new_ids.append(entry_id)
                any_new = True
                time.sleep(1)  # be gentle with Discord rate limits
            else:
                print(f"  -> FAILED to post: {entry_id}")

        if new_ids:
            state[feed_key] = list(seen_ids.union(new_ids))[-200:]  # keep state file bounded

    save_json(STATE_PATH, state)

    if not any_new:
        print("No new posts this run.")


if __name__ == "__main__":
    main()
